language: java
jdk:
  - oraclejdk8

install:
# installing srclib
  - mkdir $HOME/gocode
  - export GOPATH=$HOME/gocode
  - go get -u -v sourcegraph.com/sourcegraph/srclib/cmd/srclib
  - export PATH=$PATH:$HOME/gocode/bin
  # Build this toolchain
  - make
  - mkdir -p $HOME/.srclib/sourcegraph.com/sourcegraph
  - ln -s $TRAVIS_BUILD_DIR $HOME/.srclib/sourcegraph.com/sourcegraph/srclib-basic

script:
  - srclib test
